export const routes = {
  home: "/",
  signIn: "/sign-in",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  changePassword: "/change-password",
  onboarding: "/onboarding",
  accountInactive: "/account-inactive",
  organizationDisabled: "/organization-disabled",
  organizationUnavailable: "/organization-unavailable",
  demo: {
    chooseRole: "/demo/choose-role",
  },
  profile: {
    home: "/profile",
    workHours: "/profile/work-hours",
  },
  notifications: "/notifications",
  search: "/search",
  settings: "/settings",
  billing: "/settings/billing",
  team: "/team",
  users: {
    detail: (id: string) => `/users/${id}`,
  },
  clients: {
    home: "/clients",
    detail: (id: string) => `/clients/${id}`,
  },
  tasks: "/tasks",
  ideas: "/ideas",
  content: {
    home: "/content",
    reviews: "/content/reviews",
  },
  reviews: {
    ideas: "/reviews/ideas",
    content: "/reviews/content",
  },
  calendar: "/calendar",
  reports: "/reports",
  admin: {
    users: "/admin/users",
    invitations: "/admin/invitations",
    teams: "/admin/teams",
    tasks: "/admin/tasks",
    ideas: "/admin/ideas",
    workHours: "/admin/work-hours",
  },
  superiorAdmin: {
    home: "/super-admin",
    organizations: "/super-admin/organizations",
    organizationRequests: "/super-admin/organization-requests",
    billing: "/super-admin/billing",
    trialBlacklist: "/super-admin/trial-blacklist",
    support: "/super-admin/support",
    announcements: "/super-admin/announcements",
    auditLogs: "/super-admin/audit-logs",
    systemHealth: "/super-admin/system-health",
    organization: (id: string) => `/super-admin/organizations/${id}`,
  },
  dashboards: {
    admin: "/admin",
    marketingManager: "/marketing-manager",
    supervisor: "/supervisor",
    accountManager: "/account-manager",
    teamLead: "/team-lead",
    creator: "/creator",
    contentCreator: "/content-creator",
    graphicDesigner: "/graphic-designer",
    videoEditor: "/video-editor",
    client: "/client",
  },
} as const;
